# Generated by Django 4.0.3 on 2023-03-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('name_bank', models.CharField(max_length=20)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('from_account', models.FloatField()),
                ('to_account', models.FloatField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
